version: "3.7"

services:
  server:
    image: hashirhamid/backend:v1.1
    container_name: express
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb+srv://hashir:hashir123@db.1xy3dly.mongodb.net/?retryWrites=true&w=majority;
      - PORT=5000

  client:
    image: hashirhamid/frontend:v1.1
    container_name: react
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
